### ISSUE TITLE
empty /etc/fail2ban/ip.blacklist 

### ISSUE THREAD

**Issue by sgiannulli** [mitchellkrogza/Fail2Ban-Blacklist-JAIL-for-Repeat-Offenders-with-Perma-Extended-Banning#1]
Hello,
I know you have tested your jail on Fail2ban 0.9.1, I just want to report that with version 0.9.6 ip.blacklist file remains empty after max retry attempts are reached
`2017-03-22 19:18:06,519 fail2ban.filter         [914]: INFO    [apache] Found 10.64.64.64`
`2017-03-22 19:18:09,536 fail2ban.filter         [914]: INFO    [apache] Found 10.64.64.64`
`2017-03-22 19:18:12,552 fail2ban.filter         [914]: INFO    [apache] Found 10.64.64.64`
`2017-03-22 19:18:13,287 fail2ban.actions        [914]: NOTICE  [apache] Ban 10.64.64.64`
`2017-03-22 19:18:13,425 fail2ban.filter         [914]: INFO    [blacklist] Found 10.64.64.64`

**Comment by mitchellkrogza** [comment]
Did you make the ip.blacklist file writeable?

Try `chmod 755 /etc/fail2ban/ip.blacklist` and make sure that the file is owned by root:root

**Comment by mitchellkrogza** [comment]
Have updated Readme with better setup instructions:
https://github.com/mitchellkrogza/Fail2Ban-Blacklist-JAIL-for-Repeat-Offenders-with-Perma-Extended-Banning/blob/master/README.md

**Comment by sgiannulli** [comment]
yes, now working
fail2ban 0.9.6 on Raspbian Jessie
thanks a lot
