### ISSUE TITLE
Receive Email of Banned IP's on Fail2Ban Restart

### ISSUE THREAD

**Issue by jsmith0103** [mitchellkrogza/Fail2Ban-Blacklist-JAIL-for-Repeat-Offenders-with-Perma-Extended-Banning#3]
I was trying out your code (works very well, btw!) however I've found that if I restart Fail2Ban I receive an email for each banned IP, as if it's rescanning/processing all of the logs at startup and not excluding notifications for those in the ip.blacklist file.

Is this expected behavior?

**Comment by mitchellkrogza** [comment]
Hi Jake, I’ll update this later today for you with the way of disabling
that.

**Comment by mitchellkrogza** [comment]
So sorry @jsmith0103 I completely forgot about this. To stop the emails on startup simply change the jail settings as follows. The important addition being 
`action = %(action_)s`

```
[blacklist]
enabled = true
logpath  = /var/log/fail2ban.*
filter = blacklist
banaction = blacklist
action = %(action_)s
bantime  = 31536000   ; 1 year
findtime = 31536000   ; 1 year
maxretry = 8
```

**Comment by mitchellkrogza** [comment]
Readme updated https://github.com/mitchellkrogza/Fail2Ban-Blacklist-JAIL-for-Repeat-Offenders-with-Perma-Extended-Banning/commit/6b8a6825f519ca4b597d998f37c0fe1b4431c929

**Comment by jsmith0103** [comment]
Thank you!
